apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
  - protocol: TCP
    port: 32400
    targetPort: 32400
    nodePort: 32400
  selector:
    app: plex
  type: LoadBalancer
  loadBalancerIP: 10.0.3.22
