---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: radarr-sma-config
# spec:
#   storageClassName: nfs-client
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 100Mi