- apiVersion: apps/v1
  kind: Deployment
    name: radarr
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: radarr
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 100%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: radarr
      spec:
        containers:
        - env:
          - name: PGID
            value: "1100"
          - name: PUID
            value: "1100"
          image: mdhiggins/radarr-sma
          imagePullPolicy: Always
          name: radarr
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /config
            name: radarr-config
          - mountPath: /usr/local/sma/config
            name: radarr-sma-config
          - mountPath: /downloads
            name: downloads-data
          - mountPath: /movies
            name: movies-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-sma-config
          persistentVolumeClaim:
            claimName: radarr-sma-config
        - hostPath:
            path: /mnt/nfs/downloads
            type: ""
          name: downloads-data
        - hostPath:
            path: /mnt/nfs/Videos/Movies
            type: ""
          name: movies-data