apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-zelesny-cert
  namespace: overseerr
spec:
  commonName: overseerr.zelesny.com
  secretName: overseerr-zelesny-cert
  dnsNames:
    - overseerr.zelesny.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer