apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-cm
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211" # Optional but recommended
  PLAYERS: "16" # Optional but recommended
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  TZ: "UTC"
  COMMUNITY: "false"  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
  SERVER_NAME: "Ampd's World of Pals"
  SERVER_DESCRIPTION: ""
  AUTO_UPDATE_CRON_EXPRESSION: "0 * * * *"
  AUTO_UPDATE_ENABLED: "true"
  AUTO_UPDATE_WARN_MINUTES: "30"
  AUTO_REBOOT_CRON_EXPRESSION: "0 0 * * *"
  AUTO_REBOOT_ENABLED: "true"
  AUTO_REBOOT_WARN_MINUTES: "5"