---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    app: tautulli
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.3.19
spec:
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: http
  selector:
    app: tautulli
  type: LoadBalancer