apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - env:
        - name: DP_DISABLE_HEALTHCHECKS
          value: "xids"
        - name: TZ
          value: America/New_York
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: plexinc/pms-docker
        imagePullPolicy: Always
        name: plex
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: plex-data
        - mountPath: /config
          name: plex-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/nfs/videos
          type: ""
        name: plex-data
      - name: plex-config
        persistentVolumeClaim:
          claimName: plex-config