apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: plex
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
  rules: 
  - host: plex.apps.zelesny.com
    http:
      paths:
      - path:
        backend: 
          serviceName: plex
          servicePort: 80