apiVersion: v1
kind: Service
metadata:
  name: minecraft-public
spec:
  ports:
  - name: udp
    port: 19132
    protocol: UDP
    targetPort: 19132
  selector:
    app: minecraft-public
  type: NodePort
