apiVersion: v1
kind: Service
metadata:
  name: minecraft-public
spec:
  ports:
  - protocol: UDP
    port: 19132
    targetPort: 19132
    NodePort: 31029
  selector:
    app: minecraft-public
  type: NodePort
