apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"
          httpMethod: "POST"
        secureJsonData: {}
      
      - name: Grafana Alloy
        type: prometheus
        access: proxy
        url: http://alloy.grafana-alloy.svc.cluster.local:12345
        isDefault: false
        editable: true
        jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"
        secureJsonData: {}
      
      - name: Node Exporter
        type: prometheus
        access: proxy
        url: http://node-exporter.observability.svc.cluster.local:9100
        isDefault: false
        editable: true
        jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"
        secureJsonData: {}
