apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.3.31
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer