kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: prometheus-config-volume
#spec:
#  storageClassName: longhorn
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Mi