namespace: observability
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- claim.yaml
- service.yaml

configMapGenerator:
  - name: prometheus-config
    files:
    - configmap.yaml