namespace: observability
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- deployment.yaml
- claim.yaml
- service.yaml

configMapGenerator:
  - name: prometheus-server-conf
    files:
    - configmap.yaml