apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.3.28
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer