apiVersion: v1
kind: Service
metadata:
  name: sonarr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.3.16
spec:
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
    nodePort: 30089
  selector:
    app: sonarr
  type: LoadBalancer
