---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-public-allowlist
data:
  allowlist.json: |
    [
      {
        "ignoresPlayerLimit": true,
        "name": "xampdx85",
        "xuid": "2535411125743235"
      },
      {
        "ignoresPlayerLimit": false,
        "name": "WYOdACHILGUY",
        "xuid": "2535434248604615"
      },
      {
        "ignoresPlayerLimit": false,
        "name": "AstroX092501",
        "xuid": "2535472840364746"  
      },
      {
        "ignoresPlayerLimit": false,
        "name": "AppleAutobot",
        "xuid": "2533274903608960"
      },
      {
        "ignoresPlayerLimit": false,
        "name": "PoiNtEmOuT3",
        "xuid": "2533274842872257"
      },
      {
        "ignoresPlayerLimit": false,
        "name": "Spinzone123",
        "xuid": "2535412300857593"
      },
      {
        "ignoresPlayerLimit": false,
        "name": "CoopMan54321",
        "xuid": "2535448850100021"
      },
      {
        "ignoresPlayerLimit": false,
        "name": "Hockeygirl54321",
        "xuid": "2535447097017876"
      }
    ] 