apiVersion: batch/v1
kind: Job
metadata:
  name: minecraft-restart-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: minecraft-restart-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl rollout restart deployment/minecraft-public -n gaming
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-restart-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minecraft-restart-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minecraft-restart-binding
subjects:
- kind: ServiceAccount
  name: minecraft-restart-sa
roleRef:
  kind: Role
  name: minecraft-restart-role
  apiGroup: rbac.authorization.k8s.io 