kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pihole
    annotations:
        volume.beta.kubernetes.io/storage-class: 'nfs-client'
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: dnsmasq
    annotations:
        volume.beta.kubernetes.io/storage-class: 'nfs-client'
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 100Mi