apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: your-release-pihole-dns-tcp
  namespace: default
spec:
  clusterIP: 10.43.120.36
  clusterIPs:
  - 10.43.120.36
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    nodePort: 32471
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole-default
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
