apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: doppler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/williamzelesny/homelab-kube-cluster.git
    targetRevision: main
    path: manifests/bootstrapping/doppler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true