apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/williamzelesny/homelab-kube-cluster.git
    targetRevision: main
    path: manifests/bootstrapping/gpu-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "nvidia.com"
      kind: ClusterPolicy
      name: cluster-policy
      jsonPointers:
        - /spec/cdi
        - /spec/daemonsets
        - /spec/dcgmExporter
        - /spec/devicePlugin
        - /spec/gfd/enabled
        - /spec/migManager/config/default
        - /spec/migManager/installDir