apiVersion: v1
kind: Service
metadata:
  name: nzbget
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.3.28
spec:
  ports:
  - protocol: TCP
    port: 6789
    targetPort: 6789
    nodePort: 30556
  selector:
    app: nzbget
  type: LoadBalancer
