spec:
    spec:
      containers:
        env:
          - name: PLEX_TOKEN
            valueFrom:
              secretKeyRef:
                name: homepage-doppler-secret
                key: PLEX_TOKEN
