apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  template:
    spec:
      containers:
        - name: homepage
          env:
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homepage-doppler-secret
                  key: PLEX_TOKEN
            - name: OVERSEERR_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homepage-doppler-secret
                  key: OVERSEERR_API_TOKEN
