apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  template:
    spec:
      containers:
        - name: homepage
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "10.0.3.26:3000"
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homepage-doppler-secret
                  key: PLEX_TOKEN
            - name: OVERSEERR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-doppler-secret
                  key: OVERSEERR_API_KEY
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-doppler-secret
                  key: RADARR_API_KEY
            - name: NZBGET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: homepage-doppler-secret
                  key: NZBGET_USERNAME
            - name: NZBGET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homepage-doppler-secret
                  key: NZBGET_PASSWORD
