helmCharts:
  - name: homepage
    repo: https://jameswynn.github.io/helm-charts
    releaseName: homepage
    namespace: homepage
    valuesFile: values.yaml

namespace: homepage

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: homepage

  - path: homepage-service.yaml
    target:
      kind: Service
      name: homepage

  - path: homepage-doppler-secret.yaml
    target:
      kind: Secret
      name: homepage-doppler-secret