namespace: default
resources:
- prometheus-clusterRole.yaml
- prometheus-clusterRoleBinding.yaml
- prometheus-podDisruptionBudget.yaml
- prometheus-prometheus.yaml
- prometheus-prometheusRole.yaml
- prometheus-roleBindingConfig.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleConfig.yaml
- prometheus-roleSpecificNamespaces.yaml
- prometheus-service.yaml
- prometheus-serviceAccount.yaml
- prometheus-serviceMonitor.yaml