apiVersion: v1
data:
  agent.yaml: |
    integrations:
      node_exporter:
        enabled: true
        rootfs_path: /host/root
    metrics:
      wal_directory: /var/lib/agent/wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: AmpD
      configs:
      - name: integrations
        remote_write:
        - url: http://mimir-distributed-distributor.monitoring.svc.cluster.local:8080/api/v1/push
        scrape_configs:
        - job_name: monitoring/alertmanager
          scheme: http
          metrics_path: /metrics
          static_configs:
          - targets:
            - mimir-distributed-alertmanager-headless.monitoring.svc.cluster.local:8080
            labels:
              namespace: monitoring
        - job_name: monitoring/ingester
          scheme: http
          metrics_path: metrics
          static_configs:
          - targets:
            - mimir-distributed-ingester.monitoring.svc.cluster.local:8080
            labels:
              namespace: monitoring
        - job_name: monitoring/querier
          scheme: http
          metrics_path: metrics
          static_configs:
          - targets:
            - mimir-distributed-querier.monitoring.svc.cluster.local:8080
            labels:
              namespace: monitoring
        - job_name: monitoring/compactor
          scheme: http
          metrics_path: metrics
          static_configs:
          - targets:
            - mimir-distributed-compactor.monitoring.svc.cluster.local:8080
            labels:
              namespace: monitoring
        - job_name: integrations/kubernetes/cadvisor
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              source_labels:
                - __meta_kubernetes_node_name
              target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
        - job_name: integrations/kubernetes/kubelet
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/$1/proxy/metrics
              source_labels:
                - __meta_kubernetes_node_name
              target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: monitoring