apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-agent-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: grafana-agent
  namespaceSelector:
    any: true
  endpoints:
    - port: agent-http-metrics
      path: /metrics
---
apiVersion: v1
data:
  agent.yaml: |
    integrations:
      node_exporter:
        enabled: true
        rootfs_path: /host/root
    metrics:
      wal_directory: /var/lib/agent/wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: AmpD
      configs:
      - name: integrations
        remote_write:
        - url: http://mimir-distributed-distributor.monitoring.svc.cluster.local:8080/api/v1/push
        scrape_configs:
        - job_name: alertmanager
          scheme: http
          metrics_path: /metrics
          static_configs:
          - targets:
            - mimir-distributed-alertmanager-headless.monitoring.svc.cluster.local:8080
            labels:
            - namespace: monitoring
        - job_name: ingester
          scheme: http
          metrics_path: metrics
          static_configs:
          - targets:
            - mimir-distributed-ingester.monitoring.svc.cluster.local:8080
            labels:
            - namespace: monitoring
        - job_name: integrations/kubernetes/cadvisor
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              source_labels:
                - __meta_kubernetes_node_name
              target_label: __metrics_path__
          scheme: https
          tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
              server_name: kubernetes
        # - job_name: integrations/kubernetes/kubelet
        #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        #   kubernetes_sd_configs:
        #     - role: node
        #   relabel_configs:
        #     - replacement: kubernetes.default.svc:443
        #       target_label: __address__
        #     - regex: (.+)
        #       replacement: /api/v1/nodes/$1/proxy/metrics
        #       source_labels:
        #         - __meta_kubernetes_node_name
        #       target_label: __metrics_path__
        #   scheme: https
        #   tls_config:
        #       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        #       insecure_skip_verify: false
        #       server_name: kubernetes
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
  - kind: ServiceAccount
    name: grafana-agent
    namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: grafana-agent
  template:
    metadata:
      labels:
        name: grafana-agent
    spec:
      containers:
        - args:
            - -config.file=/etc/agent/agent.yaml
          command:
            - /bin/agent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: grafana/agent:v0.24.2
          imagePullPolicy: IfNotPresent
          name: agent
          ports:
            - containerPort: 8080
              name: http-metrics
          volumeMounts:
            - mountPath: /etc/agent
              name: grafana-agent
      serviceAccount: grafana-agent
      volumes:
        - configMap:
            name: grafana-agent
          name: grafana-agent