apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-agent-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: grafana-agent
  namespaceSelector:
    any: true
  endpoints:
    - port: agent-http-metrics
      path: /metrics
    - port: span-metrics
      path: /metrics