apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent
  name: grafana-agent
  namespace: monitoring
spec:
  ports:
    - name: agent-http-metrics
      port: 8080
      targetPort: 8080
  selector:
    name: grafana-agent
  type: NodePort
