apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: radarr
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: linuxserver/radarr:latest@sha256:f812987fe076ab652c82d5a1cb7bbd5f8e07c9a9ea932b1ad966cea44e77748a
        imagePullPolicy: Always
        name: radarr
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: radarr-config
        - mountPath: /downloads
          name: downloads-data
        - mountPath: /movies
          name: movies-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config
      - hostPath:
          path: /mnt/nfs/downloads
          type: ""
        name: downloads-data
      - hostPath:
          path: /mnt/nfs/videos/Movies
          type: ""
        name: movies-data