apiVersion: v1
kind: Service
metadata:
  name: radarr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.3.21
spec:
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
    nodePort: 30078
  selector:
    app: radarr
  type: LoadBalancer
