kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi