apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations: {}
spec:
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    app: home-assistant
  type: LoadBalancer