helmCharts:
  - name: grafana-agent-operator
    repo: https://grafana.github.io/helm-charts
    version: 0.3.6
    releaseName: grafana-agent-operator
    namespace: grafana-agent-operator
    valuesFile: values.yaml

namespace: grafana-agent-operator

resources:
  - grafana-agent-crds-grafanaagents.yaml
  - grafana-agent.yaml
  - grafana-agent-service-account.yaml
  - grafana-agent-clusterrole.yaml