apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall
spec:
  storageClassName: longhorn
  volumeName: heimdall
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi