apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: heimdall
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.3.29
spec:
  selector:
    app: heimdall
  ports:
    - name: http-80
      protocol: TCP
      port: 80
    - name: https-443
      protocol: TCP
      port: 443
  type: LoadBalancer